### ISSUE TITLE
Scrum Update - May 29, 2021

### ISSUE THREAD

**Issue by austincho** [valarao/chocolate-thunder-chess#13]
**What Did I Work on This Past Iteration**
I worked on brainstorming project task requirements with the rest of the team, reviewed a couple of short pull requests, and pushed front-end boilerplates to master.

**What Were Any Major Issues/Challenges I Ran Into**
Considering this is the beginning of the project I didn't have any major issues during this iteration. 

**What Do You Plan to Work on This Coming Iteration**
I will be looking to create issues and the front-end components related to our minimum requirements this next iteration.

**Comment by AlvinCYLo** [comment]
**What Did I Work on This Past Iteration**
I worked with the rest of the team on brainstorming a project topic to pursue, the designs we were planning to model our front-end web app around, and the overall architecture of the app in relation to what technologies we will use in class. I also worked on submitting the starter code/boilerplate for the backend express server to be used in the future.

**What Were Any Major Issues/Challenges I Ran Into**
The only challenge I ran into was probably coming up with a project idea to do and how the related technologies could be used to fulfill that goal. 

**What Do You Plan to Work on This Coming Iteration**
For this coming iteration, we will continue refining some tasks to assign to each member. We will be looking into the development of the different front-end components using react and creating a basic layout for the app.

**Comment by valarao** [comment]
**What Did I Work on This Past Iteration**
Along with my team, I worked to come up with the project idea and a very high-level design. I also wrote the project description for the README.

**What Were Any Major Issues/Challenges I Ran Into**
The primary challenge was determining a project idea that was appropriate for the technology stack and appropriate to complete over the next few months given everyone's capacity.

**What Do You Plan to Work on This Coming Iteration**
I plan to formally define a project design, work with the team to breakdown tasks, finish setting up the high level code structure, and enable CI/CD for the project. Additionally, I plan to work on at least 1-2 front end engineering tasks.

**Comment by joyx9** [comment]
**What Did I Work on This Past Iteration**
I helped to brainstorm the project idea with the team and what features we would present with our project. I also drew the sketch prototypes for what our front-end might look like for key features.

**What Were Any Major Issues/Challenges I Ran Into**
Coming up with the project idea and trying to envision what kind of goals would be a good plan for the amount of time we have to work on the project.

**What Do You Plan to Work on This Coming Iteration**
I will be setting up ESLint as well as working with the team to figure out priority of upcoming tasks and working on completing the front-end tasks.
